export const projectsData = [
  {
    id: '1',
    name: 'Imprffct games',
    date: '28.12.24',
    cover: '/preview-imprffctgames.webp',
    desktop: '/d-imprffctgames.webp',
    mobile: '/m-imprffctgames.webp',
    status: 'deployed',
    techs: ['NodeJS', 'React', 'TypesSript', 'MongoDB', 'TailwindCSS'],
    demo: 'https://imprffctgames.com/',
    github: 'https://github.com/antaga04/imprffctgames',
  },
  {
    id: '2',
    name: 'Weather app',
    date: '10.05.24',
    cover: '/preview-weather.webp',
    desktop: '/d-weatherdelta.webp',
    mobile: '/m-weatherdelta.webp',
    status: 'deployed',
    techs: ['JS', 'React'],
    demo: 'http://weatherdelta.vercel.app/',
    github: 'https://github.com/antaga04/Weather-App',
  },
  {
    id: '3',
    name: 'Square - Bill Splitter',
    date: '15.1.25',
    cover: '/preview-square.webp',
    desktop: '/d-square.webp',
    mobile: '/m-square.webp',
    status: 'deployed',
    techs: ['NodeJS', 'React', 'TypesSript', 'MongoDB', 'TailwindCSS'],
    demo: 'https://squaresplit.vercel.app/',
    github: '',
  },
  {
    id: '5',
    name: 'RGC Tools',
    date: '19.04.26',
    cover: '/preview-rgc-tools.webp',
    desktop: '/d-rgc-tools.webp',
    mobile: '',
    status: 'deployed',
    techs: ['Electron', 'TS', 'React', 'Tailwind'],
    demo: '',
    github: '',
  },
  {
    id: '6',
    name: 'Lotería Hub',
    date: '18.06.24',
    cover: '/preview-loteriaanta.webp',
    desktop: '/d-loteriaanta.webp',
    mobile: '/m-loteriaanta.webp',
    status: 'deployed',
    techs: ['TS', 'React', 'Tailwind', 'Express', 'MongoDB'],
    demo: '',
    github: '',
  },{
    id: '4',
    name: 'Nasa app',
    date: '02.10.23',
    cover: '/nasa-app.webp',
    desktop: '/d-nasa-app.webp',
    mobile: '/m-nasa-app.webp',
    status: 'deployed',
    techs: ['JS', 'React'],
    demo: 'https://apod-mars.netlify.app',
    github: 'https://github.com/antaga04/apod-mars-web',
  }
];
