export const projectsData = [
  {
    id: '4',
    name: 'Weather app',
    date: '10.05.24',
    cover: '/weather-preview.webp',
    desktop: '/d-weatherdelta.webp',
    mobile: '/m-weatherdelta.webp',
    status: 'deployed',
    techs: ['JS', 'React'],
    demo: 'http://weatherdelta.vercel.app/',
    github: 'https://github.com/antaga04/Weather-App',
  },
  {
    id: '3',
    name: 'Nasa app',
    date: '02.10.23',
    cover: '/nasa-app.webp',
    desktop: '/d-nasa-app.webp',
    mobile: '/m-nasa-app.webp',
    status: 'deployed',
    techs: ['JS', 'React'],
    demo: 'https://apod-mars.netlify.app',
    github: 'https://github.com/antaga04/apod-mars-web',
  },
  {
    id: '5',
    name: 'Games hub',
    date: '31.05.24',
    cover: '/future-project.webp',
    desktop: '',
    mobile: '',
    status: 'future',
    techs: ['JS', 'React', 'Testing'],
    demo: '',
    github: '',
  },
  {
    id: '6',
    name: 'Rest API',
    date: '09.02.24',
    cover: '/c-portfolios-api.webp',
    desktop: '/portfolios-api.webp',
    mobile: '',
    status: 'deployed',
    techs: ['Node', 'Express', 'noSQL'],
    demo: 'https://devportfolios.onrender.com/api/portfolios',
    github: 'https://github.com/antaga04/portfolios-api',
  },
  {
    id: '7',
    name: 'Relational modeling',
    date: '14.04.24',
    cover: '/c-gameshub-api.webp',
    desktop: '/gameshub-api.webp',
    mobile: '',
    status: 'deployed',
    techs: ['Node', 'Express', 'noSQL'],
    demo: 'https://backendgameshub.onrender.com/api/games',
    github: 'https://github.com/antaga04/backendGamesHub',
  },
  {
    id: '8',
    name: 'Full server',
    date: '09.04.24',
    cover: '/c-magicbooks-api.webp',
    desktop: '/books-api.webp',
    mobile: '',
    status: 'deployed',
    techs: ['Node', 'Express', 'noSQL'],
    demo: 'https://magicbooks.onrender.com/api/books',
    github: 'https://github.com/antaga04/books-api',
  },
  {
    id: '1',
    name: 'Dynamic store',
    date: '13.05.23',
    cover: '/dynamic-store.webp',
    desktop: '/d-dynamic-store.webp',
    mobile: '/m-dynamic-store.webp',
    status: 'deployed',
    techs: ['HTML', 'CSS', 'JS'],
    demo: 'https://rocksolidsounds.netlify.app/',
    github: 'https://github.com/antaga04/ss-dynamic-shop',
  },
  {
    id: '0',
    name: 'Responsive website',
    date: '08.03.23',
    cover: '/landing-page.webp',
    desktop: '/d-responsive.webp',
    mobile: '/m-responsive.webp',
    status: 'deployed',
    techs: ['HTML', 'CSS'],
    demo: 'https://landing-page-adrian-anta.netlify.app/',
    github: 'https://github.com/antaga04/web-responsive-01',
  },
];
