export const projects = [
  {
    name: 'Responsive website',
    date: '',
    cover: '',
    status: '',
    tech: ['HTML', 'CSS'],
    demo: '',
    github: '',
  },
  {
    name: 'Dynamic store',
    date: '',
    cover: '',
    status: '',
    tech: ['HTML', 'CSS', 'JS'],
    demo: '',
    github: '',
  },
  {
    name: 'Portfolio',
    date: '',
    cover: '',
    status: '',
    tech: ['HTML', 'CSS', 'JS'],
    demo: '',
    github: '',
  },
  {
    name: 'Nasa app',
    date: '',
    cover: '',
    status: '',
    tech: ['JS', 'React'],
    demo: '',
    github: '',
  },
  {
    name: 'Weather app',
    date: '',
    cover: '',
    status: '',
    tech: ['JS', 'React'],
    demo: '',
    github: '',
  },
  {
    name: 'Games hub',
    date: '',
    cover: '',
    status: '',
    tech: ['JS', 'React', 'Testing'],
    demo: '',
    github: '',
  },
  {
    name: 'Rest API',
    date: '',
    cover: '',
    status: '',
    tech: ['Node', 'Express', 'noSQL'],
    demo: '',
    github: '',
  },
  {
    name: 'Relational modeling',
    date: '',
    cover: '',
    status: '',
    tech: ['Node', 'Express', 'noSQL'],
    demo: '',
    github: '',
  },
  {
    name: 'Fulll server',
    date: '',
    cover: '',
    status: '',
    tech: ['Node', 'Express', 'noSQL', 'Testing'],
    demo: '',
    github: '',
  },
];
